resolver: lts-18.16
packages:
- autorecorder
extra-deps:
- github: NorfairKing/dirforest
  commit: 69e8ae036b047fae105c1fe990e175a7572a3eba
  subdirs:
    - dirforest
- github: NorfairKing/autodocodec
  commit: 9880ec062f1166bdac50b8eb59c6dd010bc9af0c
  subdirs:
    - autodocodec
    - autodocodec-schema
    - autodocodec-yaml
- normaldistribution-1.1.0.3@sha256:2615b784c4112cbf6ffa0e2b55b76790290a9b9dff18a05d8c89aa374b213477,2160

nix:
  shell-file: shell.nix
