name: "Nix Build"
on:
  pull_request:
  push:
    branches:
      - development
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v11
    - name: free disk space
      run: |
        sudo rm -rf /opt
    - uses: cachix/cachix-action@releases/v6
      with:
        name: autorecorder
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
